# Generated by Django 2.2.2 on 2019-08-22 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqds', '0014_auto_20190819_1858'),
        ('medals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medal_set', to='sqds.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='StatMedalRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(choices=[('level', 'Level'), ('gear', 'Gear tier'), ('rarity', 'Rarity'), ('speed', 'Speed'), ('health', 'Health'), ('protection', 'Protection'), ('physical_damage', 'Physical Damage'), ('physical_crit_chance', 'Physical CC'), ('special_damage', 'Special Damage'), ('special_crit_chance', 'Special CC'), ('crit_damage', 'Critical Damage'), ('potency', 'Potency'), ('tenacity', 'Tenacity'), ('mod_speed', 'Mod Speed'), ('mod_critical_chance', 'Mod CC'), ('mod_potency', 'Mod Potency'), ('mod_tenacity', 'Mod Tenacity')], max_length=200)),
                ('value', models.FloatField(null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_medal_rule_set', to='sqds.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='ZetaMedalRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zeta_medal_rule_set', to='sqds.Unit')),
                ('zeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sqds.Skill')),
            ],
        ),
        migrations.RemoveField(
            model_name='scorestatrule',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='scorezetarule',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='scorezetarule',
            name='zeta',
        ),
        migrations.DeleteModel(
            name='ScoredUnit',
        ),
        migrations.CreateModel(
            name='MedaledUnit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sqds.unit',),
        ),
        migrations.DeleteModel(
            name='ScoreStatRule',
        ),
        migrations.DeleteModel(
            name='ScoreZetaRule',
        ),
        migrations.AddField(
            model_name='medal',
            name='stat_medal_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medal_set', to='medals.StatMedalRule'),
        ),
        migrations.AddField(
            model_name='medal',
            name='zeta_medal_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medal_set', to='medals.ZetaMedalRule'),
        ),
    ]
