# Generated by Django 2.2.2 on 2019-08-24 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0002_auto_20190822_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zetamedalrule',
            old_name='zeta',
            new_name='skill',
        ),
        migrations.AlterField(
            model_name='medal',
            name='player_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medal_set', to='sqds.PlayerUnit'),
        ),
    ]
