# Generated by Django 2.2.2 on 2019-06-22 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gphist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gp',
            options={'ordering': ['created'], 'verbose_name': 'GP'},
        ),
    ]
