# Generated by Django 2.2.2 on 2019-07-15 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sqds', '0013_auto_20190701_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='GAPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('focus_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_pool_set', to='sqds.Player')),
            ],
        ),
        migrations.CreateModel(
            name='GAPoolPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_pool_player_set', to='ga.GAPool')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sqds.Player')),
            ],
        ),
    ]
