# Generated by Django 2.2.2 on 2019-08-04 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ga', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gapool',
            options={'verbose_name': 'GA pool'},
        ),
        migrations.AlterField(
            model_name='gapoolplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_pool_player_set', to='sqds.Player'),
        ),
    ]
