# Generated by Django 2.2 on 2019-04-22 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('sqds', '0001_initial'), ('sqds', '0002_unit'), ('sqds', '0003_playerunit'), ('sqds', '0004_playerunit_gp'), ('sqds', '0005_auto_20190420_1452'), ('sqds', '0006_auto_20190420_1500'), ('sqds', '0007_auto_20190422_1702'), ('sqds', '0008_auto_20190422_1759')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('gp', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('ally_code', models.IntegerField()),
                ('gp', models.IntegerField()),
                ('gp_char', models.IntegerField()),
                ('gp_ship', models.IntegerField()),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sqds.Guild')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.IntegerField()),
                ('level', models.IntegerField()),
                ('gear', models.IntegerField()),
                ('equipped_count', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('health', models.IntegerField()),
                ('protection', models.IntegerField()),
                ('physical_damage', models.IntegerField()),
                ('physical_crit_chance', models.FloatField()),
                ('special_damage', models.IntegerField()),
                ('special_crit_chance', models.FloatField()),
                ('crit_damage', models.FloatField()),
                ('potency', models.FloatField()),
                ('tenacity', models.FloatField()),
                ('armor', models.FloatField()),
                ('resistance', models.FloatField()),
                ('armor_penetration', models.IntegerField()),
                ('resistance_penetration', models.IntegerField()),
                ('health_steal', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_set', to='sqds.Player')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sqds.Unit')),
                ('gp', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['player__name', 'unit__name'],
            },
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['name'], name='sqds_player_name_3fc089_idx'),
        ),
        migrations.RemoveIndex(
            model_name='player',
            name='sqds_player_name_3fc089_idx',
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=200)),
                ('type', models.IntegerField()),
                ('zeta', models.BooleanField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-gp']},
        ),
        migrations.AlterField(
            model_name='player',
            name='gp',
            field=models.IntegerField(verbose_name='GP'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gp_char',
            field=models.IntegerField(verbose_name='GP (Characters)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gp_ship',
            field=models.IntegerField(verbose_name='GP (Ships)'),
        ),
        migrations.AlterField(
            model_name='playerunit',
            name='crit_damage',
            field=models.FloatField(verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='playerunit',
            name='gp',
            field=models.IntegerField(verbose_name='GP'),
        ),
        migrations.AlterField(
            model_name='playerunit',
            name='health',
            field=models.IntegerField(verbose_name='HP'),
        ),
        migrations.AlterField(
            model_name='playerunit',
            name='physical_crit_chance',
            field=models.FloatField(verbose_name='Phys. CC'),
        ),
        migrations.AlterField(
            model_name='playerunit',
            name='physical_damage',
            field=models.IntegerField(verbose_name='Phys. dmg'),
        ),
        migrations.AlterField(
            model_name='playerunit',
            name='potency',
            field=models.FloatField(verbose_name='Pot.'),
        ),
        migrations.AlterField(
            model_name='playerunit',
            name='protection',
            field=models.IntegerField(verbose_name='Prot.'),
        ),
        migrations.AlterField(
            model_name='playerunit',
            name='resistance',
            field=models.FloatField(verbose_name='Res.'),
        ),
        migrations.AlterField(
            model_name='playerunit',
            name='special_crit_chance',
            field=models.FloatField(verbose_name='Spec. CC'),
        ),
        migrations.AlterField(
            model_name='playerunit',
            name='special_damage',
            field=models.IntegerField(verbose_name='Spec. dmg'),
        ),
        migrations.AlterField(
            model_name='playerunit',
            name='tenacity',
            field=models.FloatField(verbose_name='Ten.'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['api_id'], name='sqds_unit_api_id_19be2e_idx'),
        ),
        migrations.AddField(
            model_name='skill',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sqds.Ability'),
        ),
        migrations.AddField(
            model_name='skill',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sqds.Unit'),
        ),
        migrations.AddIndex(
            model_name='ability',
            index=models.Index(fields=['api_id'], name='sqds_abilit_api_id_01f375_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['api_id'], name='sqds_skill_api_id_2ad0ac_idx'),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='type',
        ),
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ability',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='api_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sqds.Unit'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='zeta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
