# Generated by Django 2.2 on 2019-04-25 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('sqds', '0002_auto_20190424_2104'), ('sqds', '0003_playerunit_last_updated'), ('sqds', '0004_auto_20190425_1613'), ('sqds', '0005_auto_20190425_1623'), ('sqds', '0006_auto_20190425_1647')]

    dependencies = [
        ('sqds', '0001_squashed_0008_auto_20190422_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='zeta',
            new_name='isZeta',
        ),
        migrations.CreateModel(
            name='Zeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sqds.PlayerUnit')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sqds.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='playerunit',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='guild',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='guild',
            index=models.Index(fields=['api_id'], name='sqds_guild_api_id_e1ba69_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['api_id'], name='sqds_player_api_id_8df444_idx'),
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='isZeta',
            new_name='is_zeta',
        ),
    ]
