# Generated by Django 2.2 on 2019-04-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqds', '0004_playerunitgear'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='is_left_hand_g12',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gear',
            name='is_right_hand_g12',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
