# Generated by Django 2.2 on 2019-04-29 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('sqds', '0006_auto_20190428_1722'), ('sqds', '0007_auto_20190428_2053')]

    dependencies = [
        ('sqds', '0005_auto_20190426_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='playerunitgear',
            name='player_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_set', to='sqds.PlayerUnit'),
        ),
        migrations.AlterField(
            model_name='zeta',
            name='player_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zeta_set', to='sqds.PlayerUnit'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['api_id'], name='sqds_catego_api_id_7522db_idx'),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='ability',
        ),
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='api_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_zeta',
            field=models.BooleanField(),
        ),
        migrations.AddField(
            model_name='unit',
            name='categories',
            field=models.ManyToManyField(related_name='unit_set', to='sqds.Category'),
        ),
        migrations.DeleteModel(
            name='Ability',
        ),
    ]
