# Generated by Django 2.2 on 2019-04-29 15:58

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import sqds.models


class Migration(migrations.Migration):

    replaces = [('sqds', '0007_auto_20190429_1122'), ('sqds', '0008_auto_20190429_1441')]

    dependencies = [
        ('sqds', '0006_auto_20190428_1722_squashed_0007_auto_20190428_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=20)),
                ('mod_set', django_enumfield.db.fields.EnumField(default=1, enum=sqds.models.ModSet)),
                ('slot', models.IntegerField()),
                ('level', models.IntegerField()),
                ('pips', models.IntegerField()),
                ('tier', models.IntegerField()),
                ('speed', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=0)),
                ('health_percent', models.FloatField(default=0.0)),
                ('protection', models.IntegerField(default=0)),
                ('protection_percent', models.FloatField(default=0.0)),
                ('offense', models.IntegerField(default=0)),
                ('offense_percent', models.FloatField(default=0.0)),
                ('defense', models.IntegerField(default=0)),
                ('defense_percent', models.FloatField(default=0.0)),
                ('critical_chance', models.FloatField(default=0.0)),
                ('critical_damage', models.FloatField(default=0.0)),
                ('potency', models.FloatField(default=0.0)),
                ('tenacity', models.FloatField(default=0.0)),
                ('critical_avoidance', models.FloatField(default=0.0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('player_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod_set', to='sqds.PlayerUnit')),
            ],
        ),
        migrations.AddIndex(
            model_name='mod',
            index=models.Index(fields=['api_id'], name='sqds_mod_api_id_ca647f_idx'),
        ),
        migrations.AlterField(
            model_name='player',
            name='guild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sqds.Guild'),
        ),
    ]
