# Generated by Django 2.2.1 on 2019-05-10 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqds', '0007_auto_20190429_1122_squashed_0008_auto_20190429_1441'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='sqds_catego_api_id_7522db_idx',
        ),
        migrations.RemoveIndex(
            model_name='gear',
            name='sqds_gear_api_id_f26730_idx',
        ),
        migrations.RemoveIndex(
            model_name='guild',
            name='sqds_guild_api_id_e1ba69_idx',
        ),
        migrations.RemoveIndex(
            model_name='mod',
            name='sqds_mod_api_id_ca647f_idx',
        ),
        migrations.RemoveIndex(
            model_name='player',
            name='sqds_player_api_id_8df444_idx',
        ),
        migrations.RemoveIndex(
            model_name='skill',
            name='sqds_skill_api_id_2ad0ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='unit',
            name='sqds_unit_api_id_19be2e_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='api_id',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='api_id',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='guild',
            name='api_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='mod',
            name='api_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='api_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='guild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_set', to='sqds.Guild'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='api_id',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='api_id',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
