# Generated by Django 2.2.2 on 2019-06-11 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqds', '0009_auto_20190604_1735_squashed_0010_auto_20190604_2117_squashed_0010_auto_20190605_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerunitgear',
            name='player_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pug_set', to='sqds.PlayerUnit'),
        ),
        migrations.AlterField(
            model_name='scorestatrule',
            name='stat',
            field=models.CharField(choices=[('level', 'Level'), ('gear', 'Gear tier'), ('rarity', 'Rarity'), ('speed', 'Speed'), ('health', 'Health'), ('protection', 'Protection'), ('physical_damage', 'Physical Damage'), ('physical_crit_chance', 'Physical CC'), ('special_damage', 'Special Damage'), ('special_crit_chance', 'Special CC'), ('crit_damage', 'Critical Damage'), ('potency', 'Potency'), ('tenacity', 'Tenacity'), ('mod_speed', 'Mod Speed'), ('mod_critical_chance', 'Mod CC'), ('mod_potency', 'Mod Potency'), ('mod_tenacity', 'Mod Tenacity')], max_length=200),
        ),
    ]
