# Generated by Django 2.2.2 on 2019-06-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqds', '0010_auto_20190611_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='api_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='api_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='guild',
            name='api_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='mod',
            name='api_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='api_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='api_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='api_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
