# Generated by Django 2.2.2 on 2019-06-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqds', '0011_auto_20190614_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorestatrule',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='scorezetarule',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='scorezetarule',
            name='zeta',
        ),
        migrations.DeleteModel(
            name='ScoredUnit',
        ),
        migrations.DeleteModel(
            name='ScoreStatRule',
        ),
        migrations.DeleteModel(
            name='ScoreZetaRule',
        ),
    ]
