# Generated by Django 2.2.2 on 2019-07-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqds', '0012_auto_20190620_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='playerunit',
            name='accuracy',
            field=models.FloatField(default=0, verbose_name='Acc.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerunit',
            name='mod_accuracy',
            field=models.FloatField(default=0, verbose_name='Mod acc.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerunit',
            name='mod_armor',
            field=models.FloatField(default=0, verbose_name='Mod armor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerunit',
            name='mod_crit_damage',
            field=models.FloatField(default=0, verbose_name='Mod CD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerunit',
            name='mod_critical_avoidance',
            field=models.FloatField(default=0, verbose_name='Mod CA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerunit',
            name='mod_health',
            field=models.IntegerField(default=0, verbose_name='Mod HP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerunit',
            name='mod_physical_crit_chance',
            field=models.FloatField(default=0, verbose_name='Mod phys. CC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerunit',
            name='mod_physical_damage',
            field=models.IntegerField(default=0, verbose_name='Mod phys. dmg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerunit',
            name='mod_potency',
            field=models.FloatField(default=0, verbose_name='Mod pot.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerunit',
            name='mod_protection',
            field=models.IntegerField(default=0, verbose_name='Mod prot.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerunit',
            name='mod_resistance',
            field=models.FloatField(default=0, verbose_name='Mod res.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerunit',
            name='mod_special_crit_chance',
            field=models.FloatField(default=0, verbose_name='Mod spec. CC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerunit',
            name='mod_special_damage',
            field=models.IntegerField(default=0, verbose_name='Mod spec. dmg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerunit',
            name='mod_speed',
            field=models.IntegerField(default=0, verbose_name='Mod speed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerunit',
            name='mod_tenacity',
            field=models.FloatField(default=0, verbose_name='Mod ten.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='ally_code',
            field=models.IntegerField(db_index=True),
        ),
    ]
