# Generated by Django 2.2.2 on 2019-08-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqds', '0013_auto_20190701_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='guild',
            options={},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.AlterModelOptions(
            name='playerunit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={},
        ),
        migrations.AddField(
            model_name='mod',
            name='accuracy_roll',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mod',
            name='critical_avoidance_roll',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mod',
            name='critical_chance_roll',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mod',
            name='critical_damage_roll',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mod',
            name='defense_percent_roll',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mod',
            name='defense_roll',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mod',
            name='health_percent_roll',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mod',
            name='health_roll',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mod',
            name='offense_percent_roll',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mod',
            name='offense_roll',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mod',
            name='potency_roll',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mod',
            name='primary_stat',
            field=models.CharField(choices=[('OF', 'offense_percent'), ('DE', 'defense_percent'), ('PR', 'protection_percent'), ('HP', 'health_percent'), ('SP', 'speed'), ('AC', 'accuracy'), ('CA', 'critical_avoidance'), ('CC', 'critical_chance'), ('CD', 'critical_damage'), ('PO', 'potency'), ('TE', 'tenacity')], db_index=True, default='OF', max_length=50),
        ),
        migrations.AddField(
            model_name='mod',
            name='protection_percent_roll',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mod',
            name='protection_roll',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mod',
            name='speed_roll',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mod',
            name='tenacity_roll',
            field=models.SmallIntegerField(default=0),
        ),
    ]
