# Generated by Django 2.2.2 on 2019-09-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqds', '0014_auto_20190819_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerunit',
            name='relic',
            field=models.IntegerField(null=True),
        ),
    ]
